// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef __SOCKET_HEADER_PB2_H__
#define __SOCKET_HEADER_PB2_H__

#include <lwpb/lwpb.h>


// 'MessageType' enumeration values
#define SOCKET_HEADER_REQUEST 0
#define SOCKET_HEADER_RESPONSE 1

extern const struct lwpb_msg_desc lwpb_messages_socket_header[];

// Message descriptor pointers
#define socket_header_Header (&lwpb_messages_socket_header[0])

extern const struct lwpb_field_desc lwpb_fields_socket_header_header[];

// 'Header' field descriptor pointers
#define socket_header_Header_type (&lwpb_fields_socket_header_header[0])
#define socket_header_Header_service (&lwpb_fields_socket_header_header[1])
#define socket_header_Header_method (&lwpb_fields_socket_header_header[2])
#define socket_header_Header_length (&lwpb_fields_socket_header_header[3])

extern const struct lwpb_service_desc lwpb_services_socket_header[];

// Service descriptor pointers

#endif // __SOCKET_HEADER_PB2_H__
