// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include <lwpb/lwpb.h>

#include "socket_header_pb2.h"

// 'Header' field descriptors
const struct lwpb_field_desc lwpb_fields_socket_header_header[] = {
    {
        .number = 1,
        .opts.label = LWPB_REQUIRED,
        .opts.typ = LWPB_ENUM,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "type",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.int32 = 0,
#endif
    },
    {
        .number = 2,
        .opts.label = LWPB_REQUIRED,
        .opts.typ = LWPB_STRING,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "service",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.string = "",
#endif
    },
    {
        .number = 3,
        .opts.label = LWPB_REQUIRED,
        .opts.typ = LWPB_STRING,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "method",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.string = "",
#endif
    },
    {
        .number = 4,
        .opts.label = LWPB_REQUIRED,
        .opts.typ = LWPB_UINT32,
        .opts.flags = 0,
        .msg_desc = 0,
#if LWPB_FIELD_NAMES
        .name = "length",
#endif
#if LWPB_FIELD_DEFAULTS
        .def.uint32 = 0,
#endif
    },
};

// Message descriptors
const struct lwpb_msg_desc lwpb_messages_socket_header[] = {
    {
        .num_fields = 4,
        .fields = lwpb_fields_socket_header_header,
#if LWPB_MESSAGE_NAMES
        .name = "Header",
#endif
    },
};

// Service descriptors
const struct lwpb_service_desc lwpb_services_socket_header[] = {
};

