// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include <lwpb/lwpb.h>

#include "test1_pb2.h"

// 'PhoneNumber' field descriptors
const struct lwpb_field_desc lwpb_fields_test_phonenumber[] = {
    {
        .number = 1,
        .typ = LWPB_REQUIRED | LWPB_STRING,
        .msg_desc = 0,
#ifdef LWPB_FIELD_NAMES
        .name = "number",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.string = "",
#endif
    },
    {
        .number = 2,
        .typ = LWPB_OPTIONAL | LWPB_ENUM | LWPB_HAS_DEFAULT,
        .msg_desc = 0,
#ifdef LWPB_FIELD_NAMES
        .name = "type",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.int32 = 1,
#endif
    },
};

// 'Person' field descriptors
const struct lwpb_field_desc lwpb_fields_test_person[] = {
    {
        .number = 1,
        .typ = LWPB_REQUIRED | LWPB_STRING,
        .msg_desc = 0,
#ifdef LWPB_FIELD_NAMES
        .name = "name",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.string = "",
#endif
    },
    {
        .number = 2,
        .typ = LWPB_REQUIRED | LWPB_INT32,
        .msg_desc = 0,
#ifdef LWPB_FIELD_NAMES
        .name = "id",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.int32 = 0,
#endif
    },
    {
        .number = 3,
        .typ = LWPB_OPTIONAL | LWPB_STRING | LWPB_IS_DEPRECATED,
        .msg_desc = 0,
#ifdef LWPB_FIELD_NAMES
        .name = "email",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.string = "",
#endif
    },
    {
        .number = 4,
        .typ = LWPB_REPEATED | LWPB_MESSAGE,
        .msg_desc = test_PhoneNumber,
#ifdef LWPB_FIELD_NAMES
        .name = "phone",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.null = 0,
#endif
    },
};

// 'LookupResult' field descriptors
const struct lwpb_field_desc lwpb_fields_test_lookupresult[] = {
    {
        .number = 1,
        .typ = LWPB_OPTIONAL | LWPB_MESSAGE,
        .msg_desc = test_Person,
#ifdef LWPB_FIELD_NAMES
        .name = "person",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.null = 0,
#endif
    },
};

// 'Name' field descriptors
const struct lwpb_field_desc lwpb_fields_test_name[] = {
    {
        .number = 1,
        .typ = LWPB_OPTIONAL | LWPB_STRING,
        .msg_desc = 0,
#ifdef LWPB_FIELD_NAMES
        .name = "name",
#endif
#ifdef LWPB_FIELD_DEFAULTS
        .def.string = "",
#endif
    },
};

// Message descriptors
const struct lwpb_msg_desc lwpb_messages_test[] = {
    {
        .num_fields = 2,
        .fields = lwpb_fields_test_phonenumber,
#ifdef LWPB_MESSAGE_NAMES
        .name = "PhoneNumber",
#endif
    },
    {
        .num_fields = 4,
        .fields = lwpb_fields_test_person,
#ifdef LWPB_MESSAGE_NAMES
        .name = "Person",
#endif
    },
    {
        .num_fields = 1,
        .fields = lwpb_fields_test_lookupresult,
#ifdef LWPB_MESSAGE_NAMES
        .name = "LookupResult",
#endif
    },
    {
        .num_fields = 1,
        .fields = lwpb_fields_test_name,
#ifdef LWPB_MESSAGE_NAMES
        .name = "Name",
#endif
    },
};

