// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef __SOCKET_PROTOCOL_PB2_H__
#define __SOCKET_PROTOCOL_PB2_H__

#include <lwpb/lwpb.h>


// 'MessageType' enumeration values
#define SOCKET_PROTOCOL_REQUEST 0
#define SOCKET_PROTOCOL_RESPONSE 1

extern const struct lwpb_msg_desc lwpb_messages_socket_protocol[];

// Message descriptor pointers
#define socket_protocol_Header (&lwpb_messages_socket_protocol[0])

extern const struct lwpb_field_desc lwpb_fields_socket_protocol_header[];

// 'Header' field descriptor pointers
#define socket_protocol_Header_type (&lwpb_fields_socket_protocol_header[0])
#define socket_protocol_Header_service (&lwpb_fields_socket_protocol_header[1])
#define socket_protocol_Header_method (&lwpb_fields_socket_protocol_header[2])

extern const struct lwpb_service_desc lwpb_services_socket_protocol[];

// Service descriptor pointers

#endif // __SOCKET_PROTOCOL_PB2_H__
